services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-test
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo-test:/data/db
    ports:
      - 27018:27017

  postgres-db:
    image: postgres:latest
    container_name: postgres-test
    restart: unless-stopped
    environment:
      USER_UID: 1000
      USER_GID: 1000
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-test:/var/lib/postgresql/data
    ports:
      - 5432:5432
